services:

    victoire_core.widget_breadcrumb_content_resolver:
        class: Victoire\Bundle\WidgetBundle\Resolver\BaseWidgetContentResolver
        tags:
            - { name: victoire_widget.widget_content_resolver, alias: Breadcrumb }
    #alias to the entity
    victoire.widget.breadcrumb:
        class: Victoire\Widget\BreadcrumbBundle\Entity\WidgetBreadcrumb

    #alias to the form
    victoire.widget.form.breadcrumb:
        class: Victoire\Widget\BreadcrumbBundle\Form\WidgetBreadcrumbType
        tags:
            - { name: form.type , alias: victoire_widget_form_breadcrumb}

    victoire_core.widget_breadcrumb_builder:
        class: Victoire\Widget\BreadcrumbBundle\Breadcrumb\Builder\BreadcrumbBuilder
        arguments:
            - "@knp_menu.factory"

    victoire_core.twig.cms_widget_breadcrumb:
        class: Victoire\Widget\BreadcrumbBundle\Twig\Extension\WidgetBreadcrumbExtension
        arguments:
            - "@victoire_templating"
            - "@victoire_core.widget_breadcrumb_builder"
        tags:
            - { name: twig.extension }
